# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: node_modules
          # An explicit key for restoring and saving the cache
          key: node_modules

      - name: Build Optimized App
        run: |
          npm install
          npm run build

      - name: Run Tests
        run: python -m unittest discover phone_sensor

      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: '["phone_sensor/js_client --force", "."]'

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: "[Automated] build client"

          # push it in the bump version step (next)
          push: false

      # see https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
      # - name: Publish distribution 📦 to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/

      - name: Bump Version
        run: |
          pip install -U bump2version
          git fetch --depth=500 # https://stackoverflow.com/a/45993185/1266662
          git config user.name "GH Actions CI"
          git config user.email "callumjhays@gmail.com"
          bump2version patch --commit --tag \
            --current-version $(git describe --tags --abbrev=0) \
            setup.py docs/conf.py
          # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions/58035262
          git push --atomic origin ${GITHUB_REF##*/} $(git describe --tags --abbrev=0)

      - name: build PyPa distribution
        run: |
          pip install build --user
          python -m build \
            --sdist \
            --wheel \
            --outdir dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
